web/router.ex
defmodule MovieCatalog.Router do
  use MovieCatalog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MovieCatalog.Auth, repo: MovieCatalog.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MovieCatalog do
    pipe_through :browser # Use the default browser stack

    get "/", MovieController, :index

    resources "/movies", MovieController, only: [:show]
    resources "/registrations", RegistrationController, only: [:new, :create]

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/manage", MovieCatalog do
    pipe_through [:browser, :authenticate_user]

    resources "/movies", MovieController, only: [:new, :create] do
      post "/comment", MovieController, :add_comment, as: :comment
      post "/score", MovieController, :add_score, as: :score
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MovieCatalog do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule MovieCatalog.LayoutView do
  use MovieCatalog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
	<title>Movie Catalog</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>
<body>
<!-- Shell -->
<div id="shell">
	<!-- Header -->
	<div id="header">
		<h1 id="logo"><a href="#">Movie Catalog</a></h1>

		<!-- Navigation -->
		<div id="navigation">
			<ul>
			    <li><a class="active" href="#">HOME</a></li>
			    <li><a href="#">IN THEATERS</a></li>
			    <li><a href="#">COMING SOON</a></li>
          <%= if logged_in?(@conn) do %>
            <li><%= current_user(@conn).email %></li>
            <li><%= link "LOGOUT", to: session_path(@conn, :delete), method: :delete %></li>
          <% else %>
            <li><%= link "LOGIN",    to: "/login" %></li>
            <li><%= link "REGISTER", to: registration_path(@conn, :new) %></li>
          <% end %>
			    <li><%= link "ADD MOVIE", to: movie_path(@conn, :new) %></li>
			</ul>
		</div>
		<!-- end Navigation -->

		<!-- Sub-menu -->
		<div id="sub-navigation">
			<ul>
			    <li><a href="#">SHOW ALL</a></li>
			    <li><a href="#">LATEST TRAILERS</a></li>
			    <li><a href="#">TOP RATED</a></li>
			    <li><a href="#">MOST COMMENTED</a></li>
			</ul>
			<div id="search">
				<form action="home_submit" method="get" accept-charset="utf-8">
					<label for="search-field">SEARCH</label>
					<input type="text" name="search field" placeholder="Enter search here" id="search-field" title="Enter search here" class="blink search-field"  />
					<input type="submit" value="GO!" class="search-button" />
				</form>
			</div>
		</div>
		<!-- end Sub-Menu -->

	</div>
	<!-- end Header -->

	<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
	<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

	<div id="main">
		<%= render @view_module, @view_template, assigns %>
	</div>
</div>
<!-- end Shell -->
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>