web/router.ex
defmodule MovieCatalog.Router do
  use MovieCatalog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MovieCatalog.Auth, repo: MovieCatalog.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MovieCatalog do
    pipe_through :browser # Use the default browser stack

    get "/", MovieController, :index

    resources "/movies", MovieController, only: [:show]
    resources "/registrations", RegistrationController, only: [:new, :create]

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/manage", MovieCatalog do
    pipe_through [:browser, :authenticate_user]

    resources "/movies", MovieController, only: [:new, :create] do
      post "/comment", MovieController, :add_comment, as: :comment
      post "/score", MovieController, :add_score, as: :score
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", MovieCatalog do
  #   pipe_through :api
  # end
end

web/models/movie.ex
defmodule MovieCatalog.Movie do
  use MovieCatalog.Web, :model

  schema "movies" do
    field :title, :string
    field :description, :string
    field :cover_path, :string
    field :published, Ecto.Date
    belongs_to :user, MovieCatalog.User

    has_many :comments, MovieCatalog.Comment
    has_many :scores, MovieCatalog.Score

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :description, :published, :cover_path])
    |> validate_required([:title, :description, :published, :cover_path])
  end
end

web/controllers/movie_controller.ex
defmodule MovieCatalog.MovieController do
  use MovieCatalog.Web, :controller

  plug :authenticate_user when action in [:new, :create]

  alias MovieCatalog.Movie
  alias MovieCatalog.Comment
  alias MovieCatalog.Score

  def index(conn, _params, _user) do
    movies = MovieCatalog.Repo.all(Movie)
    render conn, movies: movies
  end

  def show(conn, %{"id" => movie_id}, _user) do
    movie = MovieCatalog.Repo.get(Movie, movie_id)
    movie = Repo.preload(movie, :comments)
    score = get_score(movie_id)

    IO.inspect score
    render conn, [movie: movie, score: score, changeset: Comment.changeset(%Comment{})]
  end

  def new(conn, _params, user) do
    changeset =
      user
      |> build_assoc(:movies)
      |> Movie.changeset()

    render conn, changeset: changeset
  end

  def create(conn, %{"movie" => movie_params}, user) do
    movie_params = save_file(movie_params, user)
    user = build_assoc(user, :movies)

    changeset = Movie.changeset(user, movie_params)

    case MovieCatalog.Repo.insert(changeset) do
      {:ok, _changeset} ->
        conn
        |> put_flash(:info, "Movie was published")
        |> redirect(to: "/")
      {:error, movie} ->
        conn
        |> put_flash(:info, "Unable to publish movie")
        |> render("new.html", changeset: movie)
    end
  end

  def add_score(conn, %{"movie_id" => movie_id, "score" => score}, user) do
    changeset = Score.changeset(%Score{user_id: user.id}, Map.put(score, "movie_id", movie_id))
    movie = MovieCatalog.Repo.get(MovieCatalog.Movie, movie_id)

    case MovieCatalog.Repo.insert(changeset) do
      {:ok, _changeset} ->
        conn
        |> put_flash(:info, "Movie was scored")
        |> redirect(to: movie_path(conn, :show, movie))
      {:error, score} ->
        conn
        |> put_flash(:info, "Unable to score movie")
        |> render(conn, "show.html", %{movie: movie, score: score})
    end
  end

  def add_comment(conn, %{"comment" => comment_params, "movie_id" => movie_id}, user) do
    comment_params = Map.put(comment_params, "movie_id", movie_id)

    changeset = Comment.changeset(
      %Comment{user_id: user.id},
      comment_params
    )
    movie = MovieCatalog.Repo.get(MovieCatalog.Movie, movie_id)
    case MovieCatalog.Repo.insert(changeset) do
      {:ok, _changeset} ->
        conn
        |> put_flash(:info, "Movie was published")
        |> redirect(to: movie_path(conn, :show, movie))
      {:error, changeset} ->
        conn
        |> put_flash(:info, "Unable to publish movie")
        |> render(conn, "show.html", %{movie: movie, changeset: changeset})
    end
  end

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
      [conn, conn.params, MovieCatalog.Session.current_user(conn)])
  end

  defp save_file(movie_params, user) do
    case upload = movie_params["cover"] do
      nil ->
        movie_params
      _ ->
        extension = Path.extname(upload.filename)
        cover_path = "/media/#{user.id}-#{movie_params["title"]}#{extension}"
        File.cp!(upload.path, cover_path)

        Map.put(movie_params, "cover_path", cover_path)
    end
  end

  defp get_score(movie_id) do
    score_query = from s in Score,
        where: s.movie_id == ^movie_id,
        select: %{count: count(s.id), sum: sum(s.points)}

    score = MovieCatalog.Repo.one(score_query)

    calculate_score(score.count, score.sum)
  end

  defp calculate_score(0, _), do: 0
  defp calculate_score(count, sum), do: sum / count
end

web/views/movie_view.ex
defmodule MovieCatalog.MovieView do
  use MovieCatalog.Web, :view
end

web/templates/movie/index.html.eex
<!-- Content -->
<div id="content">
  <!-- Box -->
  <div class="box">
    <div class="head">
      <h2>LATEST TRAILERS</h2>
    </div>
    <%= for movie <- @movies do %>

    <!-- Movie -->
    <div class="movie">

      <div class="movie-image">
        <a href="<%= movie_path @conn, :show, movie %>"><span class="play"><span class="name"><%= movie.title %></span></span><img src="<%= movie.cover_path %>" alt="movie" /></a>
      </div>

      <div class="rating">
        <p>RATING</p>
        <div class="stars">
          <div class="stars-in">

          </div>
        </div>
        <span class="comments">12</span>
      </div>
    </div>
    <!-- end Movie -->

    <% end %>
  </div>
  <!-- end Box -->

</div>
<!-- end Content -->

<div class="cl">&nbsp;</div>

web/templates/movie/new.html.eex
<h1>Publish movie</h1>

<%= form_for @changeset, movie_path(@conn, :create), [multipart: true], fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
    </div>
  <% end %>

  <div class="form-group">
    <label>Title</label>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <label>Description</label>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <label>Published</label>
    <%= date_select f, :published, class: "form-control" %>
    <%= error_tag f, :published %>
  </div>

  <div class="form-group">
    <label>Cover</label>
    <%= file_input f, :cover, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Publish", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/movie/show.html.eex
<%= @movie.title %> <%= @score %>
<%= @movie.description %>
<img src="<%= @movie.cover_path %>" width="150px"/>

<%= for comment <- @movie.comments do %>
  <p><%= comment.message %></p>
<% end %>

<%= form_for @conn, movie_score_path(@conn, :add_score, @movie), [as: :score], fn f -> %>
  <div class="form-group">
    <label>Points</label>
    <%= text_input f, :points, class: "form-control" %>
    <%= error_tag f, :points %>
  </div>

  <div class="form-group">
    <%= submit "Score", class: "btn btn-primary" %>
  </div>
<% end %>

<%= form_for @changeset, movie_comment_path(@conn, :add_comment, @movie), fn f -> %>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
    </div>
  <% end %>

  <div class="form-group">
    <label>Comment</label>
    <%= textarea f, :message, class: "form-control" %>
    <%= error_tag f, :message %>
  </div>

  <div class="form-group">
    <%= submit "Publish", class: "btn btn-primary" %>
  </div>
<% end %>